{
    "default_sub_language_loc":"plain",
    "default_skin":"mafia",
    "default_naming":"default",
    "default_maxplayers":10,
    "default_roles":[
        // GodFather
        "role_4",
        // Sherif
        "role_2",
        // Doctor
        "role_1",
        // Citizen
        "role_0",
        // Random Mafia Core
        "rand_6",
        // Citizen
        "role_0",
        // Random Town Power
        "rand_5",
        // Random Mafia
        "rand_1",
        // Random Town Investigative
        "rand_4",
        // Blackmailer
        "role_5",
        // Random Neutral
        "rand_2",
        // Random Town
        "rand_0",
        // Random Neutral
        "rand_2",
        // Random Mafia
        "rand_1",
        // Mayor
        "role_16",
        // Citizen
        "role_0",
        // Framer
        "role_14",
        // Random Town
        "rand_0",
        // Random Town
        "rand_0",
        // Random Mafia
        "rand_1"
    ],
    "default_gamename":"Mafia Game {0}",
    "roles":[
        {   "displayid":"citizen",      //0
            "roleid":0,
            "goal":0,
            "roleactions":[0],
            "passroleto":[],
            "subscribechat":-1,
            "subscribeactions":-1,
            "publishchat":-1,
            "publishidentity":[],
            "publishactions":-1,
            "informedallychannel":0,
            "sheriffresult":0,
            "investigateresult":"untrusting",
            "rolecategory":0
        },
        {   "displayid":"doctor",       //1
            "roleid":1,
            "goal":0,
            "roleactions":[1],
            "passroleto":[],
            "subscribechat":-1,
            "subscribeactions":-1,
            "publishchat":-1,
            "publishidentity":[],
            "publishactions":-1,
            "informedallychannel":0,
            "sheriffresult":0,
            "investigateresult":"knives",
            "rolecategory":0
        },
        {   "displayid":"sherif",       //2
            "roleid":2,
            "goal":0,
            "roleactions":[2],
            "passroleto":[],
            "subscribechat":-1,
            "subscribeactions":-1,
            "publishchat":-1,
            "publishidentity":[],
            "publishactions":-1,
            "informedallychannel":0,
            "sheriffresult":0,
            "investigateresult":"knowledge",
            "rolecategory":0
        },
        {   "displayid":"mafioso",      //3
            "roleid":3,
            "goal":1,
            "roleactions":[3],
            "passroleto":[],
            "subscribechat":0,
            "subscribeactions":0,
            "publishchat":0,
            "publishidentity":[0],
            "publishactions":0,
            "informedallychannel":1,
            "sheriffresult":1,
            "investigateresult":"knives",
            "rolecategory":1
        },
        {   "displayid":"godfather",    //4
            "roleid":4,
            "goal":1,
            "roleactions":[3],
            "passroleto":[3,5,10,13,14],
            "subscribechat":0,
            "subscribeactions":0,
            "publishchat":0,
            "publishidentity":[0],
            "publishactions":0,
            "informedallychannel":1,
            "sheriffresult":0,
            "investigateresult":"leader",
            "rolecategory":1
        },
        {   "displayid":"blackmailer",  //5
            "roleid":5,
            "goal":1,
            "roleactions":[4],
            "passroleto":[],
            "subscribechat":0,
            "subscribeactions":0,
            "publishchat":0,
            "publishidentity":[0],
            "publishactions":0,
            "informedallychannel":1,
            "sheriffresult":1,
            "investigateresult":"knowledge",
            "rolecategory":1
        },
        {   "displayid":"vigilante",    //6
            "roleid":6,
            "goal":0,
            "roleactions":[5],
            "passroleto":[],
            "subscribechat":-1,
            "subscribeactions":-1,
            "publishchat":-1,
            "publishidentity":[],
            "publishactions":-1,
            "informedallychannel":0,
            "sheriffresult":0,
            "investigateresult":"leader",
            "rolecategory":0
        },
        {   "displayid":"escort",       //7
            "roleid":7,
            "goal":0,
            "roleactions":[6],
            "passroleto":[],
            "subscribechat":-1,
            "subscribeactions":-1,
            "publishchat":-1,
            "publishidentity":[],
            "publishactions":-1,
            "informedallychannel":0,
            "sheriffresult":0,
            "investigateresult":"busy",
            "rolecategory":0
        },
        {   "displayid":"serialkiller", //8
            "roleid":8,
            "goal":2,
            "roleactions":[7],
            "passroleto":[],
            "subscribechat":-1,
            "subscribeactions":-1,
            "publishchat":-1,
            "publishidentity":[],
            "publishactions":-1,
            "informedallychannel":0,
            "sheriffresult":1,
            "investigateresult":"knives",
            "rolecategory":2
        },
        {   "displayid":"jester",       //9
            "roleid":9,
            "goal":3,
            "roleactions":[],
            "passroleto":[],
            "subscribechat":-1,
            "subscribeactions":-1,
            "publishchat":-1,
            "publishidentity":[],
            "publishactions":-1,
            "informedallychannel":0,
            "sheriffresult":0,
            "investigateresult":"busy",
            "rolecategory":2
        },
        {   "displayid":"consort",      //10
            "roleid":10,
            "goal":1,
            "roleactions":[8],
            "passroleto":[],
            "subscribechat":0,
            "subscribeactions":0,
            "publishchat":0,
            "publishidentity":[0],
            "publishactions":0,
            "informedallychannel":1,
            "sheriffresult":1,
            "investigateresult":"busy",
            "rolecategory":1
        },
        {   "displayid":"bodygaurd",    //11
            "roleid":11,
            "goal":0,
            "roleactions":[9],
            "passroleto":[],
            "subscribechat":-1,
            "subscribeactions":-1,
            "publishchat":-1,
            "publishidentity":[],
            "publishactions":-1,
            "informedallychannel":0,
            "sheriffresult":0,
            "investigateresult":"untrusting",
            "rolecategory":0
        },
        {   "displayid":"investigator", //12
            "roleid":12,
            "goal":0,
            "roleactions":[10],
            "passroleto":[],
            "subscribechat":-1,
            "subscribeactions":-1,
            "publishchat":-1,
            "publishidentity":[],
            "publishactions":-1,
            "informedallychannel":0,
            "sheriffresult":0,
            "investigateresult":"knowledge",
            "rolecategory":0
        },
        {   "displayid":"consigliere",  //13
            "roleid":13,
            "goal":1,
            "roleactions":[11],
            "passroleto":[],
            "subscribechat":0,
            "subscribeactions":0,
            "publishchat":0,
            "publishidentity":[0],
            "publishactions":0,
            "informedallychannel":1,
            "sheriffresult":1,
            "investigateresult":"knowledge",
            "rolecategory":1
        },
        {   "displayid":"framer",       //14
            "roleid":14,
            "goal":1,
            "roleactions":[12],
            "passroleto":[],
            "subscribechat":0,
            "subscribeactions":0,
            "publishchat":0,
            "publishidentity":[0],
            "publishactions":0,
            "informedallychannel":1,
            "sheriffresult":1,
            "investigateresult":"untrusting",
            "rolecategory":1
        },
        {   "displayid":"survivor",     //15
            "roleid":15,
            "goal":4,
            "roleactions":[0],
            "passroleto":[],
            "subscribechat":-1,
            "subscribeactions":-1,
            "publishchat":-1,
            "publishidentity":[],
            "publishactions":-1,
            "informedallychannel":0,
            "sheriffresult":0,
            "investigateresult":"alone",
            "rolecategory":2
        },
        {   "displayid":"mayor",        //16
            "roleid":16,
            "goal":0,
            "roleactions":[13],
            "passroleto":[],
            "subscribechat":-1,
            "subscribeactions":-1,
            "publishchat":-1,
            "publishidentity":[],
            "publishactions":-1,
            "informedallychannel":0,
            "sheriffresult":0,
            "investigateresult":"leader",
            "rolecategory":0
        },
        {   "displayid":"jailor",       //17
            "roleid":17,
            "goal":0,
            "roleactions":[14,15],
            "passroleto":[],
            "subscribechat":-1,
            "subscribeactions":-1,
            "publishchat":-1,
            "publishidentity":[],
            "publishactions":-1,
            "informedallychannel":0,
            "sheriffresult":0,
            "investigateresult":"knowledge",
            "rolecategory":0
        },
        {   "displayid":"busdriver",    //18
            "roleid":18,
            "goal":0,
            "roleactions":[16],
            "passroleto":[],
            "subscribechat":-1,
            "subscribeactions":-1,
            "publishchat":-1,
            "publishidentity":[],
            "publishactions":-1,
            "informedallychannel":0,
            "sheriffresult":0,
            "investigateresult":"alone",
            "rolecategory":0
        }
    ],
    "randomroles":[
        {   "displayid":"randomtown",               //0
            "randomroleid":0,
            "possibleroles":[0,1,2,6,7,11,12,16,17,18],
            "rolecategory":0
        },
        {   "displayid":"randommafia",              //1
            "randomroleid":1,
            "possibleroles":[3,5,10,13,14],
            "rolecategory":1
        },
        {   "displayid":"randomneutral",            //2
            "randomroleid":2,
            "possibleroles":[8,9,15],
            "rolecategory":2
        },
        {   "displayid":"randomtowncore",           //3
            "randomroleid":3,
            "possibleroles":[0,1,2],
            "rolecategory":0
        },
        {   "displayid":"randomtowninvestigative",  //4
            "randomroleid":4,
            "possibleroles":[2,12],
            "rolecategory":0
        },
        {   "displayid":"randomtownpower",          //5
            "randomroleid":5,
            "possibleroles":[11,16,17,18],
            "rolecategory":0
        },
        {   "displayid":"randommafiacore",          //6
            "randomroleid":6,
            "possibleroles":[3,5,13,14],
            "rolecategory":1
        }
    ],
    "roleactions":[
        {   "displayid":"vest",             //0
            "actionid":0,
            "action":0,
            "phase":0,
            "playerchoices":2,
            "playerchoiceeffect":0,
            "min_day":0,
            "target_count":1,
            "maxactions":1,
            "order":2,
            "collective":0,
            "targetswappable":0,
            "blockable":1,
            "requiredeffects":[]
        },
        {   "displayid":"heal",             //1
            "actionid":1,
            "action":1,
            "phase":0,
            "playerchoices":1,
            "playerchoiceeffect":0,
            "min_day":0,
            "target_count":1,
            "maxactions":-1,
            "collective":0,
            "targetswappable":1,
            "blockable":1,
            "requiredeffects":[]
        },
        {   "displayid":"interrogate",      //2
            "actionid":2,
            "action":2,
            "phase":0,
            "playerchoices":1,
            "playerchoiceeffect":0,
            "min_day":0,
            "target_count":1,
            "maxactions":-1,
            "collective":0,
            "targetswappable":1,
            "blockable":1,
            "requiredeffects":[]
        },
        {   "displayid":"eliminate",        //3
            "actionid":3,
            "action":3,
            "phase":0,
            "playerchoices":1,
            "playerchoiceeffect":0,
            "min_day":0,
            "target_count":1,
            "maxactions":-1,
            "target_icons":["M"],
            "collective":1,
            "targetswappable":1,
            "blockable":1,
            "requiredeffects":[]
        },
        {   "displayid":"silence",          //4
            "actionid":4,
            "action":4,
            "phase":0,
            "playerchoices":1,
            "playerchoiceeffect":0,
            "min_day":0,
            "target_count":1,
            "maxactions":-1,
            "target_icons":["S"],
            "collective":0,
            "targetswappable":1,
            "blockable":1,
            "requiredeffects":[]
        },
        {   "displayid":"martiallaw",       //5
            "actionid":5,
            "action":5,
            "phase":0,
            "playerchoices":1,
            "playerchoiceeffect":0,
            "min_day":2,
            "target_count":1,
            "maxactions":2,
            "collective":0,
            "targetswappable":1,
            "blockable":1,
            "requiredeffects":[]
        },
        {   "displayid":"distract",         //6
            "actionid":6,
            "action":6,
            "phase":0,
            "playerchoices":1,
            "playerchoiceeffect":0,
            "min_day":0,
            "target_count":1,
            "maxactions":-1,
            "collective":0,
            "targetswappable":1,
            "blockable":0,
            "requiredeffects":[]
        },
        {   "displayid":"murder",           //7
            "actionid":7,
            "action":7,
            "phase":0,
            "playerchoices":1,
            "playerchoiceeffect":0,
            "min_day":1,
            "target_count":1,
            "maxactions":-1,
            "collective":0,
            "targetswappable":1,
            "blockable":1,
            "requiredeffects":[]
        },
        {   "displayid":"entertain",        //8
            "actionid":8,
            "action":8,
            "phase":0,
            "playerchoices":1,
            "playerchoiceeffect":0,
            "min_day":0,
            "target_count":1,
            "maxactions":-1,
            "collective":0,
            "targetswappable":1,
            "blockable":0,
            "requiredeffects":[]
        },
        {   "displayid":"gaurd",            //9
            "actionid":9,
            "action":9,
            "phase":0,
            "playerchoices":1,
            "playerchoiceeffect":0,
            "min_day":0,
            "target_count":1,
            "maxactions":-1,
            "collective":0,
            "targetswappable":1,
            "blockable":0,
            "requiredeffects":[]
        },
        {   "displayid":"shadow",           //10
            "actionid":10,
            "action":10,
            "phase":0,
            "playerchoices":1,
            "playerchoiceeffect":0,
            "min_day":0,
            "target_count":1,
            "maxactions":-1,
            "collective":0,
            "targetswappable":1,
            "blockable":1,
            "requiredeffects":[]
        },
        {   "displayid":"research",         //11
            "actionid":11,
            "action":11,
            "phase":0,
            "playerchoices":1,
            "playerchoiceeffect":0,
            "min_day":0,
            "target_count":1,
            "maxactions":-1,
            "collective":0,
            "targetswappable":1,
            "blockable":1,
            "requiredeffects":[]
        },
        {   "displayid":"frame",            //12
            "actionid":12,
            "action":12,
            "phase":0,
            "playerchoices":1,
            "playerchoiceeffect":0,
            "min_day":0,
            "target_count":1,
            "maxactions":-1,
            "collective":0,
            "targetswappable":1,
            "blockable":1,
            "requiredeffects":[]
        },
        {   "displayid":"mayoralreveal",    //13
            "actionid":13,
            "action":13,
            "phase":2,
            "playerchoices":2,
            "playerchoiceeffect":0,
            "min_day":0,
            "target_count":1,
            "maxactions":1,
            "collective":0,
            "targetswappable":0,
            "blockable":1,
            "requiredeffects":[]
        },
        {   "displayid":"inprison",         //14
            "actionid":14,
            "action":14,
            "phase":7,
            "playerchoices":1,
            "playerchoiceeffect":0,
            "min_day":0,
            "target_count":1,
            "maxactions":-1,
            "collective":0,
            "targetswappable":0,
            "blockable":0,
            "requiredeffects":[]
        },
        {   "displayid":"execute",          //15
            "actionid":15,
            "action":15,
            "phase":0,
            "playerchoices":-1,
            "playerchoiceeffect":"inprison_jailor",
            "min_day":0,
            "target_count":1,
            "maxactions":2,
            "collective":0,
            "targetswappable":0,
            "blockable":1,
            "requiredeffects":["inprison_jailor"]
        },
        {   "displayid":"drive",            //16
            "actionid":16,
            "action":16,
            "phase":0,
            "playerchoices":1,
            "playerchoiceeffect":0,
            "min_day":0,
            "target_count":2,
            "maxactions":-1,
            "collective":0,
            "targetswappable":0,
            "blockable":1,
            "requiredeffects":[]
        }
    ]
}